### ISSUE TITLE
Add "Deactivate" Story

### ISSUE THREAD

**Issue by kellyayuen** [Dev-Ops-2021-Customers/customers#27]
**As a** user
**I need** my customer profile to be deactivated
**So that** it is no longer available

**Assumptions**
* all customers are active to start

**Acceptance Criteria:**
```
Given a customer is active
When the deactivate action is called
Then the user will be deactivated
```

**Comment by ddaisudov** [comment]
Need to modify the 'add' to leave the active status as 'active'
