### ISSUE TITLE
Add honcho to requirements.txt file

### ISSUE THREAD

**Issue by pegahnatanzi** [Dev-Ops-2021-Customers/customers#29]
**As a** developer,
**I need** to add honcho to requirements.txt file
**So that** the command ```honcho start``` works with my Procfile

**Assumptions**
* ...

**Acceptance Criteria:**
```
Given that I vagrant up, then vagrant ssh, then cd /vagrant
When I execute honcho start
Then my service will start
```

**Comment by pegahnatanzi** [comment]
*add assumptions

**Comment by ddaisudov** [comment]
Revisit story to add assumptions and edit label
