### ISSUE TITLE
setup.cfg file for nosetests

### ISSUE THREAD

**Issue by kellyayuen** [Dev-Ops-2021-Customers/customers#5]
**As a** developer
**I need** a configuration setup with nosetests
**So that** I can easily run the test suite

**Assumptions**
* Use Docker inside of Vagrant to run other 3rd party services if needed

**Acceptance Criteria:**
```
Given a setup.cfg file has been created
And there is a folder called ./tests with all test options
When I run nosetests command
Then the test suite will run
```

**Comment by ddaisudov** [comment]
Revisit this story post lecture.

**Comment by kellyayuen** [comment]
No longer need this ticket.
