### ISSUE TITLE
Read BDD Test

### ISSUE THREAD

**Issue by stephrosenthal** [Dev-Ops-2021-Customers/customers#50]
**As a** developer
**I need** to run BDD test cases for the Read feature
**So that** I can ensure the feature developed achieves the business goals

**Assumptions**
*Feature file exists
*UI exists

**Acceptance Criteria:**
```
Given a BDD test case for Read exists
When I run "behave"
Then all test steps are able to pass
```

**Comment by kellyayuen** [comment]
Closing this ticket as we do not need to create a read bdd test
