### ISSUE TITLE
Query Bug

### ISSUE THREAD

**Issue by kellyayuen** [Dev-Ops-2021-Customers/customers#62]
**As a** user
**I need** to search by ID
**So that** I can query the customer information

**Assumptions**
* using the local site

**Acceptance Criteria:**
```
Given two users are created
When you search for the second user
Then you should see the customer info of the second user
```

**Comment by mdv5** [comment]
Closing as this is not a defect. Search only works by 'name' not ID. The behavior witnessed is caused because the name field is blank when clicking search.
