### ISSUE TITLE
Delete button is giving a server error

### ISSUE THREAD

**Issue by mdv5** [Dev-Ops-2021-Customers/customers#64]
Delete button is not deleting the specified customer and is returning an error

**STEPS TO REPRODUCE**

**Pre-requisite:** A customer is created in the database
1) Enter a valid customer ID in the Customer ID field
2) Click the DELETE button

**EXPECTED RESULT**

- The customer is deleted
- A message of "success" is displayed

**OBSERVED RESULT**

- The customer is not deleted
- A message of Server Error is displayed

**Comment by mdv5** [comment]
It appears the wrong route is being called when clicking on delete (/deactivate is added to the end of the route).

**Comment by kellyayuen** [comment]
This issue is merged and done!
